/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro.youquan.wx;

/**
 *
 * @author Fitz
 */
public class WxJumpFrame extends javax.swing.JFrame {

    private WxJumpHandler wxJumpHandler;

    /**
     * Creates new form WxJumpFrame
     */
    public WxJumpFrame() {
        initComponents();
        wxJumpHandler = new WxJumpHandler(this, imageLabel);
        wxJumpHandler.loadImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        etDisPressRatio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etImageResizeRatio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSettingSave = new javax.swing.JButton();
        btnSettingCanel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etScreenshotInterval = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etAdbPath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSetting = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();
        menuScreenshot = new javax.swing.JMenu();

        settingDialog.setMaximumSize(new java.awt.Dimension(400, 400));
        settingDialog.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("距离与按压时间系数：");

        etDisPressRatio.setText("2.19");

        jLabel2.setText("图片缩放系数：");

        etImageResizeRatio.setText("1");

        jLabel3.setText("1表示不缩放，2表示缩放为原来的一半");

        btnSettingSave.setText("保存");
        btnSettingSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingSaveMouseClicked(evt);
            }
        });

        btnSettingCanel.setText("取消");
        btnSettingCanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingCanelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel4.setText("<html><a href=\"http://youquan.pro/ \">youquan.pro</a></html>");

        jLabel5.setText("截图间隔：");

        etScreenshotInterval.setText("2500");

        jLabel6.setText("毫秒");

        jLabel7.setText("adb路径：");

        etAdbPath.setText("adb");

        jLabel8.setText("adb有加path的，直接填adb，留空白会用默认的");

        javax.swing.GroupLayout settingDialogLayout = new javax.swing.GroupLayout(settingDialog.getContentPane());
        settingDialog.getContentPane().setLayout(settingDialogLayout);
        settingDialogLayout.setHorizontalGroup(
            settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingDialogLayout.createSequentialGroup()
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingDialogLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settingDialogLayout.createSequentialGroup()
                                .addComponent(btnSettingSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSettingCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(settingDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etDisPressRatio, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(etImageResizeRatio))
                            .addGroup(settingDialogLayout.createSequentialGroup()
                                .addComponent(etScreenshotInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))))
                    .addGroup(settingDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(etAdbPath, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        settingDialogLayout.setVerticalGroup(
            settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etDisPressRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etImageResizeRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etScreenshotInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(etAdbPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addGroup(settingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSettingSave)
                    .addComponent(btnSettingCanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        menuSetting.setText("设置");
        menuSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSettingMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSetting);

        menuExit.setText("退出");
        jMenuBar1.add(menuExit);

        menuScreenshot.setText("重新截图");
        menuScreenshot.setMargin(new java.awt.Insets(0, 160, 0, 0));
        menuScreenshot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuScreenshotMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuScreenshot);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        wxJumpHandler.onImageMouseClicked(evt);
    }//GEN-LAST:event_imageLabelMouseClicked

    private void menuScreenshotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuScreenshotMouseClicked
        wxJumpHandler.loadImage();
    }//GEN-LAST:event_menuScreenshotMouseClicked

    private void btnSettingSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingSaveMouseClicked

        String disPressRatioStr = etDisPressRatio.getText();
        float disPressRatio = 0;
        try {
            disPressRatio = Float.parseFloat(disPressRatioStr);
        } catch (Exception e) {
              wxJumpHandler.showErrorMsg("请输入有效的距离与按压时间系数");
            return;
        }
        if (disPressRatio <= 0) {
            wxJumpHandler.showErrorMsg("距离与按压时间系数必须大于0");
            return;
        }
        float imageResizeRatio = 0;
        String imageResizeRatioStr = etImageResizeRatio.getText();
        try {
            imageResizeRatio = Float.parseFloat(imageResizeRatioStr);
        } catch (Exception e) {
             wxJumpHandler.showErrorMsg("请输入有效的图片缩放系数");
            return;
        }
        if (imageResizeRatio <= 0) {
             wxJumpHandler.showErrorMsg("图片缩放系数必须大于0");
            return;
        }
        
        String screenshotIntervalStr = etScreenshotInterval.getText();
        long screenshotInterval = 0;
         try {
             screenshotInterval = Long.parseLong( screenshotIntervalStr);
        } catch (Exception e) {
             wxJumpHandler.showErrorMsg("请输入有效的截图间隔时间");
            return;
        }
        if ( screenshotInterval <500) {
             wxJumpHandler.showErrorMsg("截图间隔时间必须大于500");
            return;
        }
         String adbPath = etAdbPath.getText();
        wxJumpHandler.updateConfig(disPressRatio, imageResizeRatio,screenshotInterval ,adbPath);
        
        settingDialog.setVisible(false);
    }//GEN-LAST:event_btnSettingSaveMouseClicked

    private void btnSettingCanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingCanelMouseClicked
        settingDialog.setVisible(false);
    }//GEN-LAST:event_btnSettingCanelMouseClicked

    private void menuSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSettingMouseClicked
         settingDialog.setVisible(true);
         settingDialog.setTitle("设置");
         wxJumpHandler.displayLastConfig(etDisPressRatio, etImageResizeRatio,etScreenshotInterval,etAdbPath);
    }//GEN-LAST:event_menuSettingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WxJumpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WxJumpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WxJumpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WxJumpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WxJumpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSettingCanel;
    private javax.swing.JButton btnSettingSave;
    private javax.swing.JTextField etAdbPath;
    private javax.swing.JTextField etDisPressRatio;
    private javax.swing.JTextField etImageResizeRatio;
    private javax.swing.JTextField etScreenshotInterval;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuScreenshot;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JDialog settingDialog;
    // End of variables declaration//GEN-END:variables
}
